In [14]:
import os
import pandas as pd
import numpy as np

import tensorflow as tf
from tensorflow import keras

model = tf.keras.models.load_model('/Users/Kelly/Desktop/Test/project_28/python_scripts/nine-sensor-model/lstm')
model.summary()

Model: "sequential_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
lstm_4 (LSTM)                (None, 100)               44000     
_________________________________________________________________
dropout_4 (Dropout)          (None, 100)               0         
_________________________________________________________________
dense_8 (Dense)              (None, 100)               10100     
_________________________________________________________________
dense_9 (Dense)              (None, 4)                 404       
Total params: 54,504
Trainable params: 54,504
Non-trainable params: 0
_________________________________________________________________


In [71]:
#loading raw data
path = 'MovementAAL/new_dataset/stream_004'
sequences = []

for i in range (10,51):
    file_path = path + str(i) + '.csv'
    df = pd.read_csv(file_path, header=0, usecols=["delta1", "delta2", "delta3", "delta4", "delta5", "delta6", "delta7", "delta8", "delta9"])
    values = df.values
    sequences.append(values)
    
sequences = np.array(sequences)
   
#sequences = np.rot90(sequences[0])
print(sequences)
print(type(sequences))

#[[[ 9x55 2d array ]],[[ 9x55 2d array ]]]

[[[ 3  2 -2 ...  1  2  1]
  [ 3  2 -2 ...  0  2  1]
  [ 2  1 -1 ...  0 -1  0]
  ...
  [ 1  0  0 ... -4  2  2]
  [ 1  0 -1 ...  1  0  1]
  [ 1  0 -1 ...  1  0  0]]

 [[ 2  1 -1 ... -1 -1  1]
  [ 2  1  1 ... -1 -1  1]
  [ 3  1  0 ... -1  1  2]
  ...
  [ 2  0  1 ...  2  0  0]
  [ 1 -1  1 ...  2  1  1]
  [ 1  1  1 ...  2  1  1]]

 [[ 1  1  1 ... -2  0  0]
  [ 1  1  0 ... -2  0  0]
  [ 1  1  0 ... -2  1  0]
  ...
  [ 1  1  2 ... -1  1  2]
  [ 2  0  0 ... -1  1  1]
  [ 2  0  0 ... -1  1  1]]

 ...

 [[-1  0 -2 ...  1  1  0]
  [-1  0 -1 ...  1  1  0]
  [-1  0 -1 ...  2  1  0]
  ...
  [-1  1 -2 ...  1  1  2]
  [ 0  0 -2 ...  1  1 -1]
  [ 0  0 -3 ...  1  1  2]]

 [[ 0  1  0 ...  2  2  2]
  [ 2  0  0 ...  1  2  3]
  [ 2 -1  0 ...  2  2  3]
  ...
  [-1  0  0 ...  3  1  3]
  [-1  0 -2 ...  3  1  1]
  [-1  0 -2 ...  2  1  1]]

 [[ 3  2 -2 ...  2  2  2]
  [ 3  2 -2 ...  2  2  2]
  [ 1  2  0 ...  2  1  3]
  ...
  [ 1  0 -1 ...  1  1 -1]
  [ 1  0 -1 ...  2  1 -1]
  [ 0  1  1 ...  2  1  1]]]
<class 'nu

In [72]:
sequences[0]

array([[ 3,  2, -2,  0,  1,  1,  1,  2,  1],
       [ 3,  2, -2,  0,  0,  1,  0,  2,  1],
       [ 2,  1, -1,  0,  0,  2,  0, -1,  0],
       [ 2,  1, -1,  0, -1,  2, -1, -1,  0],
       [ 2,  1, -1,  1, -1,  0, -1, -1,  0],
       [ 1,  2,  1,  0,  1, -2,  0, -1,  1],
       [ 1,  2,  1,  0,  1, -2,  0, -1,  1],
       [ 1,  2,  1,  0,  1, -2,  0, -1, -1],
       [ 1,  0,  2,  0,  1,  0,  1, -1, -1],
       [-2,  2,  2, -2,  1,  0,  1, -1,  0],
       [-2,  2,  2, -2,  1,  0,  1,  1,  2],
       [ 2,  2,  5, -2,  2,  3, -1,  2,  3],
       [ 2,  3,  5,  0,  3,  4, -1,  2,  3],
       [ 2,  6,  5,  0,  8,  5, -1,  4,  5],
       [ 9, 21,  3,  7, 19,  6,  4, 10,  5],
       [13, 28,  3, 10, 30,  6,  5, 16,  7],
       [18, 32,  0, 13, 40,  5,  5, 18,  7],
       [18, 32,  0, 13, 46,  5,  5, 18,  7],
       [18, 32,  0, 13, 46,  5,  5, 18,  7],
       [18, 29,  0, 13, 46,  5,  5, 18,  7],
       [18, 27,  0, 13, 47,  5,  5, 18,  7],
       [18, 25,  0, 13, 47,  5,  5, 18,  7],
       [18

In [70]:
test_preds = model.predict_classes(sequences)
print(test_preds)

[3 3 3 3 0 1 1 1 0 3 2 3 3 3 3 1 3 2 3 3 3 1 0 1 3 1 3 3 1 1 3 1 1 3 1 1 3
 3 0 3 3]


In [37]:
from numpy import mean
from numpy import std
from numpy import dstack
from pandas import read_csv
from keras.utils import to_categorical

# load a dataset group, such as train or test
def load_dataset_group(group, prefix=''):
    filepath = prefix + group + '/'
    # load all 9 files as a single array
    filenames = list()
    for n in range(1,10):
        filenames += ['sensor'+ str(n) + '-' + group + '.txt']

    X = load_group(filenames, filepath)
    # load class output
    y = load_file(prefix + group + '/' + group + '-features.txt')
    return X, y

# load the dataset, returns train and test X and y elements
def load_dataset(prefix=''):
	# load all train
	trainX, trainy = load_dataset_group('train', prefix)
	print(trainX.shape, trainy.shape)
	# load all test
	testX, testy = load_dataset_group('test', prefix)
	print(testX.shape, testy.shape)

	# zero-offset class values
	trainy = trainy - 1
	testy = testy - 1

	# one hot encode y
	trainy = to_categorical(trainy)
	testy = to_categorical(testy)
	print(trainX.shape, trainy.shape, testX.shape, testy.shape)

	return trainX, trainy, testX, testy

# load a list of files into a 3D array of [samples, timesteps, features]
def load_group(filenames, prefix=''):
	loaded = list()
	for name in filenames:
		data = load_file(prefix + name)
		# print("Data: ", data)
		loaded.append(data)
		# print("loaded: ", loaded)
	# stack group so that features are the 3rd dimension
	loaded = dstack(loaded)
	
	return loaded

# load a single file as a numpy array
def load_file(filepath):
	dataframe = read_csv(filepath, header=None, delim_whitespace=True)
	# print("load_file: ", dataframe.values)
	return dataframe.values

Using TensorFlow backend.


In [58]:
trainX, trainy, testX, testy = load_dataset()
print(type(testX))
print(type(testX[0]))
print(testX)
print(testX[0])


(300, 55, 9) (300, 1)
(100, 55, 9) (100, 1)
(300, 55, 9) (300, 4) (100, 55, 9) (100, 4)
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>
[[[ 1  1 -2 ...  1  0  3]
  [ 1  1  1 ...  1  0  3]
  [ 1  1  1 ...  1  0  3]
  ...
  [ 2  0 -1 ...  1 -1  3]
  [ 1  0 -1 ...  1 -1  2]
  [ 1  0 -1 ...  1  1  2]]

 [[ 2  1 -1 ...  0  0  1]
  [ 2  1  2 ...  1  0  0]
  [ 0  1  2 ...  1  0  0]
  ...
  [ 0  0  0 ...  1  0  0]
  [-1  0  0 ...  1 -1  0]
  [-1  0  0 ...  1 -1 -1]]

 [[-1  1  2 ...  1  0  2]
  [-1  1  2 ...  1  0  1]
  [-1  1  2 ...  1  0  0]
  ...
  [ 4  1  1 ... -1  0  2]
  [ 0 -1  1 ...  2  1  2]
  [ 1  1  0 ...  1  2  2]]

 ...

 [[ 1  1 -1 ... -1  0  1]
  [ 1  1  0 ...  0  0  2]
  [ 0 -2  0 ...  1  0  2]
  ...
  [ 1 -1  0 ...  2 -1  0]
  [ 1 -1 -1 ...  1  0  1]
  [ 1  0 -1 ...  1  0  1]]

 [[ 0 -1 -1 ...  0 -1  0]
  [ 0 -1 -1 ... -1 -1  0]
  [ 0  1  0 ... -1 -1  0]
  ...
  [ 3  0  0 ... -1 -2 -1]
  [ 1 -1 -3 ... -2 -1 -1]
  [ 1  1 -3 ... -2 -1 -1]]

 [[-1 -1 -2 ... -2 -1 -2]
  [ 0 -1 -2 